spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mcm?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul
    username: root
    password:
    thymeleaf:
      cache: false
      prefix: file:src/main/resources/templates/
    jpa:
      properties:
        hibernate:
          format_sql: 'true'
          show_sql: 'true'
      hibernate:
        ddl-auto: create
      subject:
        member:
          registration: Thank you for joining our site!
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 500MB
  file:
    root:
      path: C:\Users\hanjaehyun\Pictures\genFile
    origin:
      Path: /upload/