spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 9c2486951c7643769da2abc6da8d5b9e
  mail:
    host: smtp.gmail.com
    port: 587
    username: usedcoding@gmail.com
    password: gjwwiejaguixcffq
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname
